# sound evaluation parameters
SAMPLERATE: 16000
TIME_SEGMENT_SIZE: 0.1
STEPS_BETWEEN_WINDOWS: 10
STEPS_IN_WINDOW: 5
WINDOW_GAP_RANGE: 2

INVALID_BEFORE_RANGE_START: 10
INVALID_BEFORE_RANGE_VAR: 10

# output parameters
TRAIN_STEPS_PER_SAVE: 2000000
TRAIN_STEPS_PER_PRINT: 50000
NUM_REFERENCE_VECS: 1000

# model parameters
NUM_MEL_BINS: 64
HIDDEN_SIZE: 128
OUTPUT_VECTOR_SIZE: 32

# traning parameters
SAMPLES_PER_SONG: 64
SONGS_PER_BATCH: 32
ADAM_learning_rate: 0.001
MAG_REGULARIZATION_PARAM: 0.0001 # seems to work well around 0.0001

# dataset parameters
MAX_NUM_FILES: 25

# hardware parameters
USE_GPU: False
