# sound evaluation parameters
SAMPLERATE: 16000
TIME_SEGMENT_SIZE: 0.1

STEPS_BETWEEN_WINDOWS: 10
STEPS_IN_WINDOW: 5
WINDOW_GAP_RANGE: 2

INVALID_BEFORE_RANGE_START: 10
INVALID_BEFORE_RANGE_VAR: 10

# output parameters
TRAIN_STEPS_PER_SAVE: 20000000
TRAIN_STEPS_PER_PRINT: 100000
NUM_REFERENCE_VECS: 4000

# model parameters
NUM_MEL_BINS: 80
HIDDEN_SIZE: 512
OUTPUT_VECTOR_SIZE: 80

# traning parameters
SAMPLES_PER_SONG: 256
SONGS_PER_BATCH: 4
ADAM_learning_rate: 0.001

# dataset parameters
MAX_NUM_FILES: 10000

# hardware parameters
USE_GPU: True
